Models/Topic.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GeeksForLess_Forum.Models
{
    public class Topic
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Display(Name = "Name of Article")]
        public string Name { get; set; }
        public string Text { get; set; }
        [Display(Name = "Author")]
        public string UserEmail { get; set; }
        public virtual User User { get; set; }
        public virtual List<Comment> Comments { get; set; } = new List<Comment>();
    }
}

Controllers/CommentController.cs
using GeeksForLess_Forum.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace GeeksForLess_Forum.Controllers
{
    public class CommentController : Controller
    {
        private readonly ForumContext _context;
        public CommentController(ForumContext context) => _context = context;
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(string text)
        {
            Comment comment = new Comment() { Text = text };
            if (ModelState.IsValid)
            {
                
                User owner = await _context.Users.FirstOrDefaultAsync(u => u.Email == TempData["UserEmail"].ToString());
                TempData.Keep();

                if (owner != null)
                    comment.User = owner;

                int selectedTopic = (int)TempData["SelectedTopic"];
                TempData.Keep();

                Topic topic = await _context.Topics.FirstOrDefaultAsync(t => t.Id == selectedTopic);
                if (topic != null)
                    comment.Topic = topic;

                _context.Comments.Add(comment);
                _context.SaveChanges();

                return RedirectToAction("Details", "Topic", new { Id = selectedTopic });
            }
            return View(comment);
        }

        public async Task<IActionResult> Remove(int? Id)
        {
            if (Id == null)
            {
                return new StatusCodeResult(404);
            }
            Comment comment = await _context.Comments.FindAsync(Id);
            if (comment == null)
            {
                return NotFound();
            }

            _context.Comments.Remove(comment);
            _context.SaveChanges();

            int selectedTopic = (int)TempData["SelectedTopic"];
            TempData.Keep();

            return RedirectToAction("Details", "Topic", new { Id = selectedTopic });
        }


        public async Task<IActionResult> Edit(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var comment = await _context.Comments.FindAsync(Id);
            if (comment == null)
            {
                return NotFound();
            }
            return View(comment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Id, [Bind("Id, User, UserEmail, Topic, TopicId, Text")] Comment comment)
        {
            if (Id != comment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Comments.Contains(comment))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                int selectedTopic = (int)TempData["SelectedTopic"];
                TempData.Keep();

                return RedirectToAction("Details", "Topic", new { Id = selectedTopic });
            }
            return View(comment);
        }
    }
}

Controllers/TopicController.cs
using GeeksForLess_Forum.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace GeeksForLess_Forum.Controllers
{
    public class TopicController : Controller
    {
        private readonly ForumContext _context;
        public TopicController(ForumContext context) => _context = context;
        public IActionResult Index()
        {
            var topics = _context.Topics.Select(t => t);
            return View(topics.ToList());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Topic topic)
        {
            if (ModelState.IsValid)
            {
                User owner = await _context.Users.FirstOrDefaultAsync(u => u.Email == TempData["UserEmail"].ToString());
                TempData.Keep();

                if (owner != null)
                    topic.User = owner;

                _context.Topics.Add(topic);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(topic);
        }

        public async Task<IActionResult> Details(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var topic = await _context.Topics.FirstOrDefaultAsync(m => m.Id == Id);
            if (topic == null)
            {
                return NotFound();
            }

            TempData["SelectedTopic"] = topic.Id;

            return View((topic, new Comment()));
        }

        public async Task<IActionResult> Edit(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var topic = await _context.Topics.FindAsync(Id);
            if (topic == null)
            {
                return NotFound();
            }
            return View(topic);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int Id, [Bind("Id, User, UserEmail, Name, Text")] Topic topic)
        {
            if (Id != topic.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(topic);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Topics.Contains(topic))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(topic);
        }

        public async Task<IActionResult> Remove(int? Id)
        {
            if (Id == null)
            {
                return new StatusCodeResult(404);
            }
            Topic topic = await _context.Topics.FindAsync(Id);
            if (topic == null)
            {
                return NotFound();
            }

            _context.Topics.Remove(topic);
            _context.SaveChanges();

            return RedirectToAction("Index", "Topic");
        }
    }
}

Views/Topic/Create.cshtml
@model GeeksForLess_Forum.Models.Topic

<h2 align="center">Creating New Topic</h2>
<form method="post" asp-controller="Topic" asp-action="Create">
    <div asp-validation-summary="ModelOnly"></div>
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" placeholder="Enter name">
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Text">Text</label>
        <textarea asp-for="Text" class="form-control" placeholder="Your text here" cols="75" rows="3"></textarea>
        <span asp-validation-for="Text"></span>
    </div>
    <button type="submit" class="btn btn-primary">Post</button><br><br>
</form>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Topic/Details.cshtml
@model (GeeksForLess_Forum.Models.Topic, GeeksForLess_Forum.Models.Comment)

@{
    ViewBag.Title = "Details";
}

<h2>@Html.DisplayFor(model => model.Item1.Name)</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Item1.UserEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item1.UserEmail)
            <hr />
        </dd>

        <dd>
            @Html.DisplayFor(model => model.Item1.Text)
        </dd>
    </dl>
    <div class="display-label"><br><b>Comments</b><br></div>
    <hr />
    <dl>
        @foreach (Comment c in Model.Item1.Comments)
        {
        <dt>
            @c.UserEmail @if (c.UserEmail == TempData["UserEmail"].ToString())
            {
                TempData.Keep();
                @Html.ActionLink("Edit", "Edit", "Comment", new { Id = c.Id })
                <span> - </span>
                @Html.ActionLink("Delete", "Remove", "Comment", new { Id = c.Id })
            }
            else
                TempData.Keep();
        </dt>
            <dd>
                @c.Text
            </dd>

            <dd></dd>
        }
    </dl>
</div>

@using (Html.BeginForm("Create", "Comment", FormMethod.Post))
{
    <textarea name="text" placeholder="Your text here" cols="75" rows="3"></textarea>
    <br>
    <button type="submit" class="btn btn-primary">Comment</button>
    <br>
}



<p>
    @*<button onclick="location.href='@Url.Action("Create", "Comment")';return false;"
            class="btn btn-primary">
        Leave Opinion
    </button>*@
    @*Html.ActionLink("Leave Opinion", "Create", "Comment")*@
    <br>
    <br>
    @Html.ActionLink("Back to List", "Index")
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")*@
</p>

Views/Topic/Edit.cshtml
@model GeeksForLess_Forum.Models.Topic

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="User" />
            <input type="hidden" asp-for="UserEmail" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <textarea asp-for="Text" class="form-control" rows="15"></textarea>
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Topic/Index.cshtml
@model IEnumerable<GeeksForLess_Forum.Models.Topic>

@{
    ViewBag.Title = "Articles";
}

<h2>All Our Articles</h2>

<p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserEmail)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserEmail)
                </td>

                <td>
                    @Html.ActionLink("Read", "Details", new { id = item.Id })
                    @if (item.UserEmail == TempData["UserEmail"].ToString())
                    {
                        TempData.Keep();
                        <span> - </span>
                        @Html.ActionLink("Edit ", "Edit", new { id = item.Id })
                        <span> - </span>
                        @Html.ActionLink("Delete", "Remove", new { id = item.Id })
                    }
                    else
                        TempData.Keep();
                </td>
            </tr>
        }

    </table>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col text-center">
                <button onclick="location.href='@Url.Action("Create", "Topic")';return false;" class="btn btn-primary">
                    Create New Topic
                </button>
            </div>
        </div>
    </div>
    